version: '3'

services:
  web:
    restart: always
    build: .
    # command: ["run", "--allow-env", "--allow-net", "--unstable", "server.ts"]
    container_name: PeakInsights_apis
    ports:
      - "81:81"
