version: '3.8'

services:
  web:
    restart: always
    build: .
    network_mode: host
    # command: ["run", "--allow-env", "--allow-net", "--unstable", "server.ts"]
    container_name: peakbooks_recurrrings
