version: '3'

services:
  web:
    restart: always
    build: .
    # command: ["-c", "tsconfig.json", "--allow-env", "--allow-net", "--unstable", "server.ts"]
    container_name: PeakInsights_apis
    ports:
      - "8090:8090"
