export const DATABASE: string = "peakbooks";
export const TABLE = {
  CUSTOMER: "customers",
  CUSTOMER_MORE: "customers_more",
  USERS: "users",
  INVOICES: "invoices",
  ESTIMATES: "estimates",
  INVOICE_ITEMS: "invoice_items",
  ESTIMATE_ITEMS: "estimate_items",
  ITEMS: "items",
  INCOME: "Uscers",
  PAYMENT_RECEIVED: "payment_method",
  CASH_BANK: "cash_bank",
  BANK: "bank",
  DEPOSIT_TO: "deposit_to",
  PAYMENT_RECEIVED_PAY: "payment_received",
  PAYMENT_RECEIVED_PAY_BILL: "payment_received_bills",
  RECURRING_INVOICE: "recurring_invoices",
  CREDIT_NOTE: "credit_note",
  CREDIT_NOTE_VENDOR: "credit_note_vendor",
  CREDIT_NOTE_ITEMS: "credit_items_vendor",
  BILL_ITEMS: "bill_items",
  SALES_PERSON: "sales_person",
  INVESTMENT: "investments",
  VERIFICATION: "verification",
  CREDIT_ITEMS: "credit_items",
  VENDORS: "vendors",
  EXPENSES: "expenses",
  RECURRING_EXPENSE: "recurring_expenses",
  BILLS: "billings",
  RECURRING_BILLS: 'recurring_bills',
  TAX_RATES: 'tax_rates',
  PASSWORD_RESET: 'password_reset',
  DOCUMENTS: 'documents',
  JOURNAL_ITEMS: 'journal_items',
  JOURNALS: 'journals',

  CURRENCY: 'currency',

  MPESA_PAYMENT: 'mpesa_payments'

};