export default interface  Customers {
  id?: number,
  email?: string,
  msisdn?:string,
  client_id?:string,
  customer_type?:string,
  title?:string,
  first_name?:string,
  other_name?:string,
  company_name?:string,
  customer_display_name?:string,
  website?:string,
  page_number?:number,
  offset?:number,
  mobile?:any,
  filter_value?:any,
  street?:string,
  customer_id?:string,
  city_town?:string,
  state_province?:string,
  country?:string,
  notes?:string,
  street1?:string,
  state_province1?:string,
  country1?:string,
  city_town1?:string,
  payment_method?:string,
  delivery_method?:string,
  terms?:string,
  out_of_balance?:string
}