export default interface User {
  first_name?: string,
  last_name?: string,
  msisdn?: string,
  role_id?: number,
  industry?: string,
  email?: string,
  company_name?: string,
  postal_address?: string,
  page_number?: number,
  offset?: number,
  mobile?: any,
  filter_value?: any,
  password?: string,
  id?: string,
  first_time?: string,
  our_client?: string,
  paid?: string,
  subscription?: string,
  code?: string,
  currency?: string,
  admin_role?: string,
  url?: string,
  business_pin?: string,
  financial_year?: string,
  currency_against_kenya?: string,
  expired?: string
}